import Layout from "@/layout/Layout";
import PageBanner from "@/layout/PageBanner";

const MAAS = () => {
  return (
    <Layout pageName={"MAAS"}>
      <PageBanner pageName={"MAAS"} imageURL={"img/hero/head_MAAS_background.png"} />
      <div className="neoh_fn_MAASpage">
        <section id="information" className="main_padding">
          <div className="container">
            {/* Guarantee List */}
            <p className="fn_desc fn_animated_text">
              NeoTech's primary objective is to offer 3D Mapping As a Service 
              to the entire Web3 ecosystem by securely listing and managing 
              our data on the blockchain.
            </p>
            <p className="fn_desc fn_animated_text">
              Our assets are exclusive to our virtual ecosystem, 
              ensuring they remain secured and protected. 
              Data is stored on SSD DePin nodes and hashed to ZKP ERC20 rollups and our dedicated servers, accessible only to verified data owners.
            </p>
            <p className="fn_desc fn_animated_text">
              Users can mint, trade, rent, or subscribe to assets on our marketplace 
              by connecting their decentralized wallets, ensuring complete privacy with 
              no personal information stored. Renters benefit from asset usage within the ecosystem, 
              while subscribers can access unowned assets for a limited time, providing flexibility and maximizing asset utility.
            </p>
          </div>
        </section>

        <section id="video">
          <div className="neoh_fn_video">
            <div className="bg_overlay">
              {/* Video element that plays automatically, loops, and redirects on click */}
              <a href="https://youtu.be/OWq8WarE7KY?feature=shared" target="_blank" rel="noopener noreferrer">
                <video
                  className="bg_video"
                  src="/img/MAAS/MAAS_movie.mp4"
                  autoPlay
                  loop
                  muted
                  playsInline
                  style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                />
              </a>
             {/* <div className="bg_color" /> */}
            </div>
            <div className="v_content">
              <a
                className="popup-youtube"
                href="https://youtu.be/OWq8WarE7KY?feature=shared"
                target="_blank"
                rel="noopener noreferrer"
              >
                <img src="svg/play.svg" alt="" className="fn__svg" />
              </a>
            </div>
          </div>
          {/* !Video Shortcode */}
        </section>

        <section id="information" className="main_padding">
          <div className="container">
            {/* Guarantee List */}
            <p className="fn_desc fn_animated_text">
              Clients will be able to pay in $NEOT tokens for our 3D
              personalized scanning services, with prices based on the token’s
              value at the time of purchase.
            </p>
            <p className="fn_desc fn_animated_text">
              Once they purchase our service, they could create their own
              immersive experiences within our virtual platform using their own 3D models as well as
              listing their own assets on our proprietary marketplace for
              everyone while gaining access to terabytes of Point-Cloud data we already have in store that is used for Smart City
              technologies.
            </p>
            <p className="fn_desc fn_animated_text">
              Our Clients will receive 10% of the revenue generated by the sales
              of their assets that will be listed on our marketplace if they
              wish to make it public on our platform.
            </p>
          </div>
        </section>
      </div>
    </Layout>
  );
};

export default MAAS;
